//require('./cef/Customchat/index.js')
require('./cef/MainMenu/index.js')
require('./cef/Garage/index.js')
require('./cef/Inventory/index.js')
// require('./cef/Speedometer/index.js')
require('./cef/Outfit-Selection/index.js')
require('./cef/HUD/index.js')
require('./utils/index.js')

require('./cef/garageEvents.js')
